### ISSUE TITLE
Logo proposal for PAPIER

### ISSUE THREAD

**Issue by ggabogarcia** [s1pierro/FiberFold#1]
Hello, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by s1pierro** [comment]
Hello, your contribution is welcome, especially since the logo currently used is a very poor draft one,  made quickly, in the state of mind: "having a logo is better than nothing".

**Comment by ggabogarcia** [comment]
Thank you, sir, I going to make some sketches. :)

**Comment by s1pierro** [comment]
Ok, thanks, you might want to know that i'm french, and this is the first time that I receive contribution proposal.

**Comment by s1pierro** [comment]
AND the first fully usable release is scheduled in about 2 weeks.

**Comment by ggabogarcia** [comment]
I'm glad to know, sir, I'm from Venezuela, but I currently live in Peru.  :)

**Comment by ggabogarcia** [comment]
That's great, so it will come out with the new logo proposal :)

**Comment by s1pierro** [comment]
As you say, great. Your contribution encourages me to work for a better quality result, code side and documentation side.
thanks

**Comment by ggabogarcia** [comment]
Hello again :) I present my proposal. When I entered the test mode in Papier, the first thing that came to mind were the triangles, I decided to work with them, I gave them a three-dimensional touch to each one and I used the initial of the name. I hope you like it. You can suggest anything you want. My [inspiration](https://i.imgur.com/RjtC6wy.png) .
![papier](https://user-images.githubusercontent.com/35750428/40808728-ae9f292e-64ed-11e8-84b3-02abebe89dae.png)

**Comment by s1pierro** [comment]
That's really impressive,
Indeed, the trangles are an essential component of the application. Besides, the work you've done is of remarkable quality.
The logo expresses very clearly the function of the application. And with great elegance.
For sure, I'm ok for a pull request!

I immediately update the concerned files(readme.md, index.html ...).Currently they still bear the old name of the application, "paperseed".
Then you'll be free to fork and make a pull request.
I also add in advance, your name and a link to your github profiles in the contributor list.

Again, GG!

PS: a small website is also planned, to provide help and documentation about the code. And maybe a support for donations. Your logo will also be used if you agree. I don't expect to receive many donations, but they will be shared with you.

**Comment by s1pierro** [comment]
Maybe, you could also produce a banner version to put in the MD file as you did with Chat Analyser.

**Comment by ggabogarcia** [comment]
I am very happy that you liked the proposal, perfect, let me group the files, load them in G-drive and I will send the link. One more question, do you need the logo in different sizes? I could give them to you and thus speed up the work. :)

**Comment by ggabogarcia** [comment]
This work is totally free, it is my contribution for your incredible project :)

**Comment by ggabogarcia** [comment]
Do not forget to send me the different sizes in which you need the logo :)

**Comment by s1pierro** [comment]
Hi, A big THANK YOU.
I thought you might want to use the official github method to highlight your contribution. But, using google drive and inserting your content into the project by myself is no problem.
You will anyway be added to the list of contributors in the various documents related to the project.
About the sizes, the only particular need is the browser favicon (32*32). Otherwise, a high resolution of about 256*256 will allow me to meet all future needs.
Right now I'm still very focused on the heart of the application. (automatic pattern layout, tongue and assembly mark generator).
In order to make the app utilisable as soon as possible. :)

**Comment by ggabogarcia** [comment]
All right sir, I already sent the files to your email :).

**Comment by ggabogarcia** [comment]
![DERECHOS.jpg](https://cdn.steemitimages.com/DQmVSH7hxt3nuyDxNRdWUBUBtfR11TyvLxM1F1C4vYW5UzG/DERECHOS.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

**Comment by s1pierro** [comment]
Ok, I notice that, about licence. I'll have a look about compatibility with the one I used ( GNU/GPL v3 ) I don't know if protect the work included as CC. If not, I will adapt/modify Mine.
Feel free to tell me if any mistake is done, in any document related to, or into the App :)

**Comment by ggabogarcia** [comment]
I don't think you have any problem with the license :)

**Comment by s1pierro** [comment]
Thank you, you confirm what my research was starting to tell me.
so I updated this:
![capture d ecran de 2018-06-03 17-38-01](https://user-images.githubusercontent.com/6394332/40888452-8b4e6aa4-6757-11e8-9ced-09018004abf1.png)
Feel free:
 - to report an error.
 - make any suggestion.

You should tell me if you prefer links to your github profiles or your email address.

I'm also interested in your opinion on the startup screen. I hesitate between a white background and the image currently in place. ( estetically but also in relation to loading time)
Any other suggestion about the design of the application, its layout is also welcome.

oh, I almost forgot: The SVG format files ( my favorites since I use Inkscape) you sent me are **PERFECT**! :)

**Comment by ggabogarcia** [comment]
That is really great :1st_place_medal: . You can put them in my github profile :),  hice un diseño para el fondo de la pantalla de inicio y para el archivo Léame :).Espero te gusten.

![banner 1](https://user-images.githubusercontent.com/35750428/40888963-cc4d1f24-6724-11e8-9e38-a89f9b36d596.png)
#
![banner 2](https://user-images.githubusercontent.com/35750428/40888964-cc7421e6-6724-11e8-955c-cda36284aa6b.png)

**Comment by ggabogarcia** [comment]
Here is a model to better [explain](https://i.imgur.com/DvrE6BU.png) the idea :)

**Comment by s1pierro** [comment]
Wow, Neat ! I  just ... love ... that start screen.

lol (-_-*) Tengo que confesar que estoy usando DeepL para traducir al español. No he estado hablando español desde hace 20 años.

**Comment by s1pierro** [comment]
Can you send me an SVG version of this?
Anyway I'm gonna include it. But Svg can be directly included into HTML, that speed up loading.

**Comment by s1pierro** [comment]
That will come at the very end, but right now, I can say that start screen **will** be animated, shape by shape, to figure the loading. Grouped rotating first then explode to the sides when loading complete !

**Comment by ggabogarcia** [comment]
Sent to your email :)

**Comment by s1pierro** [comment]
a little precision, I saw you forked the repository.
If you localy run the app , the example buttons wont work. You'll have to use upload feature instead.
